# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-26 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_carouselimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselimage',
            name='subtitle',
            field=models.CharField(default='test', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='title',
            field=models.CharField(default='test', max_length=250),
            preserve_default=False,
        ),
    ]
