# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-09 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20180209_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
