# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-10 16:05
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_galleryimage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerypage',
            name='description',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
