# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-23 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_contactpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='zoom',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='address',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='location',
            field=models.CharField(max_length=250),
        ),
    ]
