# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-23 12:54
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_contactpage_address_and_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactpage',
            old_name='address_and_contact',
            new_name='contact',
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='address',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
