# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-23 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20180223_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='map_address',
            field=models.CharField(default='technic-alu', max_length=250),
            preserve_default=False,
        ),
    ]
