# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-23 15:35
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_contactpage_map_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='other_info',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
